apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymybuddy-backend
  namespace: paymybuddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paymybuddy-backend
  template:
    metadata:
      labels:
        app: paymybuddy-backend
    spec:
      containers:
      - name: backend
        image: paymybuddy-backend:latest  # Remplace par ton image Docker si nécessaire
        imagePullPolicy: Never
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://paymybuddy-db:3306/paymybuddy?useSSL=false"
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            configMapKeyRef:
              name: paymybuddy-config
              key: SPRING_DATASOURCE_USERNAME
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: paymybuddy-secret
              key: SPRING_DATASOURCE_PASSWORD
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: paymybuddy-backend
  namespace: paymybuddy
spec:
  selector:
    app: paymybuddy-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
