apiVersion: v1
kind: ConfigMap
metadata:
  name: paymybuddy-config
  namespace: paymybuddy
data:
  SPRING_DATASOURCE_URL: "jdbc:mysql://paymybuddy-db:3306/paymybuddy"
  SPRING_DATASOURCE_USERNAME: "paymybuddy"

---
apiVersion: v1
kind: Secret
metadata:
  name: paymybuddy-secret
  namespace: paymybuddy
type: Opaque
data:
  SPRING_DATASOURCE_PASSWORD: "cGFzc3dvcmQ="  # Base64 de "password"
